baseURL = "https://example.com"
languageCode = "en-us"
title = "Showcase Theme"
Paginate = 1000
googleAnalytics = ""
theme = "showcase"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

# this setting should always be set to false, otherwise it will break the section navigation bar
pluralizelisttitles = false

[params]
  author = "showcase"
  description = "Minimal, one page, theme for showcasing your work"
  message = ""
  hideAutoMenu = false
  
  # Pagination options
  paginate = 3
  multipage = true

[[menu.main]]
  name = "External"
  url = "https://example.com"

[social]
  facebook = "https://facebook.com"
  twitter = "https://twitter.com"
  instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"